name: build-image
on:
  workflow_dispatch: # allow manually triggering builds
  push:
    paths-ignore:
      - '**/release-please.yml'
      - '**/vulnerability-scan.yml'
      - "**.md"
      - "**/.gitkeep"
      - "renovate.json"
  schedule:
    - cron: '10 0 * * 1' # build at 00:05 UTC on Monday

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
    IMAGE_TAGS: latest
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        containerfile: 
          - boxkit
    steps:
      # Clone code to runner
      - name: Checkout
        uses: actions/checkout@v4

      # Build metadata
      - name: Image Metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ matrix.containerfile }}
          labels: |
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/ublue-os/boxkit/main/README.md

      # Build image using Buildah action
      - name: Build Image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: |
            ./ContainerFiles/${{ matrix.containerfile }}
          image: ${{ matrix.containerfile }}
          tags: ${{ env.IMAGE_TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          oci: true

      # Workaround bug where capital letters in your GitHub username make it impossible to push to GHCR.
      # https://github.com/macbre/push-to-ghcr/issues/12
      - name: Lowercase Registry
        id: registry_case
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_REGISTRY }}

      - run: podman history ${{ steps.build.outputs.image }}:${{ steps.build.outputs.tags }}

      - name: podman push ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build.outputs.image }}:${{ steps.build.outputs.tags }}
        if: github.event_name != 'pull_request'
        id: push
        env:
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ github.token }}
        run: |
          set -euo pipefail

          echo "${{ secrets.SIGNING_SECRET }}" >"${HOME}"/cosign.key

          # https://github.com/containers/image/issues/1613#issuecomment-1188923320
          # https://github.com/containers/image/blob/main/docs/containers-registries.d.5.md#individual-configuration-sections
          PODMAN_CONFDIR="$HOME/.config/containers/registries.d"
          PODMAN_CONFIG="${PODMAN_CONFDIR}/registries.yaml"

          mkdir -p "${PODMAN_CONFDIR}"
          echo "creating: ${PODMAN_CONFIG}"
          tee "${PODMAN_CONFIG}" <<EOF
          default-docker:
            use-sigstore-attachments: true
          EOF

          podman push
            --remove-signatures \
            --compression-format=zstd:chunked \
            --sign-by-sigstore-private-key="${HOME}"/cosign.key \
            --creds="${{ env.REGISTRY_USER }}:${{ env.REGISTRY_PASSWORD }}" \
            ${{ steps.build.outputs.image }}:${{ steps.build.outputs.tags }} \
            ${{ steps.registry_case.outputs.lowercase }}/${{ steps.build.outputs.image }}:${{ steps.build.outputs.tags }}
