name: vulnerability-scan
on:
  schedule:
    - cron:
        '55 0 * * *' # scan at 0:55 UTC daily
  push:
    paths-ignore:
      - '**/build-image.yml'
      - '**/release-please.yml'
      - "**.md"
      - "**/.gitkeep"
      - "renovate.json"
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
env:
  REPO_OWNER: ${{ github.repository_owner }}
jobs:
  scan:
    name: Scan Custom Image
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      contents: read
      packages: read
    strategy:
      fail-fast: true
      matrix:
        package:
          - boxkit
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Force repository owner to lowercase
        run: echo "IMAGE_REF=ghcr.io/${REPO_OWNER@L}/${{ matrix.package }}" >> ${GITHUB_ENV}

      - name: Wait up to 1m to compensate for rate limiting
        run: sleep $((RANDOM % 60))

      - name: Generate SARIF for Custom Image with Trivy
        uses: aquasecurity/trivy-action@0.31.0
        with:
          format: sarif
          github-pat: ${{ secrets.GITHUB_TOKEN }}
          image-ref: "${{ env.IMAGE_REF }}"
          output: trivy-results.sarif
          scan-type: image
          scanners: vuln
          severity: MEDIUM,HIGH,CRITICAL
        env:
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: trivy-${{ matrix.package }}
          sarif_file: trivy-results.sarif
